name: Bug Report
description: File a bug/error report!
labels: ["bug","triage"]
assignees:  ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
