name: Bug Report
title: "Bug: "
description: File a bug/error report!
labels: ["bug","triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before we begin...
        1. Please search your issue in this tracker using key words and phrases.
        2. Ensure this bug is reproducible with *just* Legion (and any Legion produced compatibility mods)
        3. If you're unsure, please visit [our discord](https://discord.com/invite/eWz2xPXdeq) [#tech-support-general](https://discord.com/channels/461042140756180992/795755741553360946), and ask a few questions
  - type: checkboxes
    id: mod-selection
    attributes:
      label: Mod
      description: Which mod(s) were you using?
      options:
        - label: "Legion: The Definitive Edition (Test Build)"
        - label: "Legion: Core (Stable)"
        - label: "Legion: Insurrection"
        - label: "Legion: Dissension"
        - label: "Legion: Reforged (Reforger)"
  - type: textarea
    id: bug-info
    attributes:
      label: Errors and Other information
      description: What happened? 
      value: |
        Example
        ##### Description:
        Legion is a bad mod and it causes my server to crash. Please git gud. You guys are doing terrible.
        
        ##### How to Reproduce:
        Add Legion to server. Watch fire. Cry.
        
        ##### Relevant Files/Information:
        ![Sad boi Ani](https://tenor.com/view/i-hate-you-anakin-darth-vader-vader-star-wars-gif-13071041)
  - type: input
    id: contact-info
    attributes:
      label: Contact Info (optional)
      description: Optional discord, username, email, etc. if we need further information
      placeholder: "@CoolGuy1999"
    validations:
      required: false

        
