name: Bug Report
title: "Bug: "
description: File a bug/error report!
labels: ["bug","triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before we begin...
        1. Please search your issue in this tracker using key words and phrases.
        2. Ensure this bug is reproducible with *just* Legion (and any Legion produced compatibility mods)
        3. If you're unsure, please visit [our discord](https://discord.com/invite/eWz2xPXdeq) [#tech-support-general](https://discord.com/channels/461042140756180992/795755741553360946), and ask a few questions
  - type: checkboxes
    label: Mod
    id: mod-selection
    attributes:
      description: Which mod(s) were you using?
      validations:     
        required: true
      options:
        - label: "Legion: The Definitive Edition (Test Build)"
        - label: "Legion: Core (Stable)"
        - label: "Legion: Insurrection"
        - label: "Legion: Dissension"
        - Label: "Legion: Reforged (Reforger)"
  - type: input
    id: contact-info
    validations:
      required: false
    attributes:
      label: Contact Info (optional)
      description: Optional discord, username, email, etc. if we need further information
      placeholder: "@CoolGuy1999"

        
