blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.com/invite/eWz2xPXdeq
    about: Interact with the Legion community!
  - name: Steam Workshop
    url: https://steamcommunity.com/id/LSDevAccount/myworkshopfiles/
    about: Check out our workshop
 
